In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digit = load_digits()
digit

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
df = pd.DataFrame(digit.data , columns =digit.feature_names)

In [6]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [7]:
df["target"] = digit.target
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [8]:
df[df["target"] == 1]

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1           0.0        0.0        0.0       12.0       13.0        5.0   
11          0.0        0.0        0.0        0.0       14.0       13.0   
21          0.0        0.0        0.0        2.0       16.0       16.0   
42          0.0        0.0        0.0        0.0       12.0        5.0   
47          0.0        0.0        0.0        1.0       11.0        9.0   
...         ...        ...        ...        ...        ...        ...   
1752        0.0        0.0        4.0       10.0       12.0        7.0   
1757        0.0        0.0        4.0       16.0       16.0        8.0   
1760        0.0        0.0        1.0       12.0       10.0        3.0   
1766        0.0        0.0        8.0       12.0       11.0        6.0   
1774        0.0        0.0        6.0       12.0       12.0        6.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
11          1.0        0.0        0.0        0.0  ...        0.0        0.0   
21          2.0        0.0        0.0        0.0  ...        0.0        0.0   
42          0.0        0.0        0.0        0.0  ...        0.0        0.0   
47          0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1752        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1757        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1760        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1766        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1774        0.0        0.0        0.0        0.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
1           0.0        0.0       11.0       16.0       10.0        0.0   
11          0.0        0.0        1.0       13.0       16.0        1.0   
21          0.0        0.0        2.0       12.0       15.0        4.0   
42          0.0        0.0        3.0       16.0        8.0        0.0   
47          0.0        0.0        2.0       14.0        6.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1752        0.0        1.0        9.0       10.0        0.0        0.0   
1757        0.0        6.0       12.0       12.0        2.0        0.0   
1760        0.0        1.0        7.0       12.0       10.0        0.0   
1766        0.0        4.0       11.0       12.0        7.0        0.0   
1774        0.0        2.0       11.0       10.0        4.0        0.0   

      pixel_7_7  target  
1           0.0       1  
11          0.0       1  
21          0.0       1  
42          0.0       1  
47          0.0       1  
...         ...     ...  
1752        0.0       1  
1757        0.0       1  
1760        0.0       1  
1766        0.0       1  
1774        0.0       1  

[182 rows x 65 columns]

In [9]:
df[df["target"] == 2].head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
2         0.0        0.0        0.0        4.0       15.0       12.0   
12        0.0        0.0        5.0       12.0        1.0        0.0   
22        0.0        0.0        8.0       16.0        5.0        0.0   
50        0.0        0.0        0.0        5.0       14.0       12.0   
51        0.0        0.0        0.0        3.0       15.0       10.0   

    pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
2         0.0        0.0        0.0        0.0  ...        0.0        0.0   
12        0.0        0.0        0.0        0.0  ...        2.0        0.0   
22        0.0        0.0        0.0        1.0  ...        0.0        0.0   
50        2.0        0.0        0.0        0.0  ...        0.0        0.0   
51        1.0        0.0        0.0        0.0  ...        0.0        0.0   

    pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
2         0.0        0.0        3.0       11.0       16.0        9.0   
12        0.0        3.0       11.0        8.0       13.0       12.0   
22        0.0        7.0       12.0       12.0       12.0       13.0   
50        0.0        0.0        6.0       12.0       13.0        3.0   
51        0.0        0.0        4.0        9.0       14.0        7.0   

    pixel_7_7  target  
2         0.0       2  
12        4.0       2  
22        1.0       2  
50        0.0       2  
51        0.0       2  

[5 rows x 65 columns]

In [10]:
len(df)

1797

In [11]:
from sklearn.model_selection import train_test_split
df["target_name"] = df.target.apply(lambda x: digit.target_names[x])
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  target  \
0        6.0       13.0       10.0        0.0        0.0        0.0       0   
1        0.0       11.0       16.0       10.0        0.0        0.0       1   
2        0.0        3.0       11.0       16.0        9.0        0.0       2   
3        7.0       13.0       13.0        9.0        0.0        0.0       3   
4        0.0        2.0       16.0        4.0        0.0        0.0       4   

   target_name  
0            0  
1            1  
2            2  
3            3  
4            4  

[5 rows x 66 columns]

In [22]:
df.index[0]

0

In [12]:
X = df.drop(["target" , "target_name"] , axis = "columns")
y = df.target

In [13]:
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size=0.2)

In [14]:
len(X_train)

1437

In [15]:
len(X_test)

360

In [16]:
from sklearn.svm import SVC
model = SVC()

In [17]:
model.fit(X_train , y_train)

SVC()

In [18]:
model.score(X_test , y_test)

0.9861111111111112

In [23]:
model.predict(X_test)

array([0, 1, 6, 1, 6, 2, 7, 9, 3, 8, 5, 0, 3, 0, 8, 7, 6, 6, 5, 7, 9, 7,
       0, 6, 8, 6, 4, 9, 6, 5, 1, 4, 0, 6, 9, 7, 7, 9, 2, 0, 2, 8, 7, 9,
       7, 2, 9, 9, 9, 7, 3, 1, 3, 0, 7, 4, 4, 6, 5, 8, 0, 7, 3, 4, 5, 8,
       3, 5, 6, 2, 7, 9, 1, 3, 5, 4, 9, 4, 8, 8, 7, 8, 0, 0, 5, 9, 1, 4,
       9, 8, 7, 1, 4, 1, 1, 1, 1, 2, 1, 5, 8, 0, 4, 3, 9, 6, 1, 7, 8, 8,
       8, 7, 9, 7, 5, 4, 4, 7, 0, 3, 7, 8, 1, 6, 1, 7, 5, 7, 1, 2, 9, 4,
       1, 2, 5, 0, 8, 7, 1, 9, 0, 1, 0, 8, 6, 0, 4, 6, 9, 4, 9, 4, 0, 8,
       8, 2, 6, 4, 1, 6, 8, 3, 0, 1, 0, 2, 2, 1, 7, 7, 7, 1, 3, 7, 0, 3,
       0, 1, 1, 4, 7, 6, 8, 1, 9, 1, 4, 6, 2, 3, 6, 4, 2, 0, 0, 9, 1, 8,
       3, 6, 0, 0, 5, 5, 6, 7, 7, 5, 0, 6, 0, 2, 2, 5, 5, 2, 7, 9, 9, 2,
       8, 2, 0, 9, 5, 2, 4, 6, 6, 4, 3, 5, 3, 0, 5, 2, 8, 1, 3, 2, 4, 7,
       7, 1, 7, 0, 4, 3, 4, 4, 9, 1, 3, 5, 5, 4, 7, 2, 7, 4, 4, 7, 5, 2,
       0, 4, 8, 6, 6, 1, 8, 7, 6, 6, 0, 0, 0, 0, 4, 7, 4, 4, 9, 2, 4, 7,
       0, 5, 7, 7, 7, 1, 9, 2, 5, 5, 5, 2, 2, 3, 4,

In [24]:
model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([4])

In [30]:
row=df.iloc[22]   #we can see a particular row with values using this.
row.to_string()

'pixel_0_0       0.0\npixel_0_1       0.0\npixel_0_2       8.0\npixel_0_3      16.0\npixel_0_4       5.0\npixel_0_5       0.0\npixel_0_6       0.0\npixel_0_7       0.0\npixel_1_0       0.0\npixel_1_1       1.0\npixel_1_2      13.0\npixel_1_3      11.0\npixel_1_4      16.0\npixel_1_5       0.0\npixel_1_6       0.0\npixel_1_7       0.0\npixel_2_0       0.0\npixel_2_1       0.0\npixel_2_2      10.0\npixel_2_3       0.0\npixel_2_4      13.0\npixel_2_5       3.0\npixel_2_6       0.0\npixel_2_7       0.0\npixel_3_0       0.0\npixel_3_1       0.0\npixel_3_2       3.0\npixel_3_3       1.0\npixel_3_4      16.0\npixel_3_5       1.0\npixel_3_6       0.0\npixel_3_7       0.0\npixel_4_0       0.0\npixel_4_1       0.0\npixel_4_2       0.0\npixel_4_3       9.0\npixel_4_4      12.0\npixel_4_5       0.0\npixel_4_6       0.0\npixel_4_7       0.0\npixel_5_0       0.0\npixel_5_1       0.0\npixel_5_2       3.0\npixel_5_3      15.0\npixel_5_4       5.0\npixel_5_5       0.0\npixel_5_6       0.0\npixel_5_7   